### ISSUE TITLE
Would you mind including this project on PyPi

### ISSUE THREAD

**Issue by hfsf** [ReactionMechanismGenerator/PyDAS#11]
Hey,

Great project. Great tool.
I would like to know, do you have any plans on distributing this tool under pypi? It would be wonderful if user could use pip or easy_install for installation of this package.

**Comment by mliu49** [comment]
Hi, thanks for your interest in this project! We currently don't have any plans for distributing this on pypi. However, this is available through the Anaconda platform (https://anaconda.org/rmg/pydas). I would encourage you to try Anaconda if possible, since it provides easy installation of many packages which are not available through pip while also supporting pip packages.

**Comment by hfsf** [comment]
Thanks for the answer. 

Currently my problem is that anaconda only provides a version of PyDAS compatible with python27, however, I would liek to use python3+. Do you guys have any plans on releasing pydas for newer python versions? I guess it would take a few development hours (if so). I've tried to port to python3 myself changing the makefile and stuff but the package does not seem to appear in my conda env. Perhaps, you could provide an official release for python3+.

**Comment by JacksonBurns** [comment]
Python 3 compatible builds are now available, see the closing comment on #14.

We will not distribute PyDAS via PyPI.
